### ISSUE TITLE
Log collection for applications in K8s cluster

### ISSUE THREAD

**Issue by supereagle** [supereagle/experiences#18]
Requirements for log collection:
- **No Invasive**: No need to modify applications
- **Low Cost**: No need to run log collector in `EVERY` pod

**Comment by supereagle** [comment]
## Overview
![image](https://cloud.githubusercontent.com/assets/3390333/24141848/b3e0fccc-0e5f-11e7-8b61-f029aee5ebdb.png)

## Process
1. Create log folder for each pod through [Pod initialization](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/container-init.md)
   **Init Script**:
```
mkdir -f /docker/logs/${APP_NAME}/${POD_NAME}
rm -rf /apps/logs
ln -s /docker/logs/${APP_NAME}/${POD_NAME} /apps/logs
```
2. Create pod by spec with env and mount
```
spec:
  containers:
  - env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    volumeMounts:
    - mountPath: /docker/logs/
      name: applogs
  volumes:
  - hostPath:
      path: /apps/logs/
    name: applogs
```
3. Startup application in pod and it will output their logs into `/apps/logs` as before
4. Log collector in each K8s node will collect app logs from host path `/apps/logs/`, and reports the logs to log server
