### ISSUE TITLE
Service account for K8s cluster

### ISSUE THREAD

**Issue by supereagle** [supereagle/experiences#32]
There is an error when create pod:
```
Error from server: error when creating "nginx.yaml": Pod "nginx" is forbidden: no API token found for service account default/default, retry after the token is automatically created and added to the service account
```

nginx.yml for pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "1"
```

Envs:
* Kubernetes: v1.5.2
* Docker: v1.12.6
