### ISSUE TITLE
Image entrypoint does not work in k8s pod

### ISSUE THREAD

**Issue by supereagle** [supereagle/experiences#48]
Deploy [MongoDB v3.6.4](https://github.com/docker-library/mongo/tree/master/3.6) in k8s, its entrypoint does not work, so the init DB scripts in `/docker-entrypoint-initdb.d/` does not run.

**Error Deployment:**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mgo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mgo
  template:
    metadata:
      labels:
        app: mgo
    spec:
      containers:
      - name: mgo
        command:
        - mongod
        - "--replSet"
        - rs0
        - "--bind_ip"
        - 0.0.0.0
        - "--smallfiles"
        - "--noprealloc"
        image: mongo:3.6.4
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        ports:
        - containerPort: 27017
```

## Reason

K8s uses `spec.template.spec.containers[0].command` for the command run by the container, and use `args` for arguments passed to the command. 

![image](https://user-images.githubusercontent.com/3390333/40435745-ed3e53a4-5ee3-11e8-90d9-49136dd50048.png)

## Reference

* https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/
